# Generated by Django 2.2.9 on 2020-01-30 04:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
