# Generated by Django 2.2.9 on 2020-02-09 01:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_student_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
