# Generated by Django 2.2.9 on 2020-07-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200709_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='danceclass',
            name='image',
            field=models.CharField(default='img/class.jpg', max_length=50),
            preserve_default=False,
        ),
    ]
