# Generated by Django 2.2.9 on 2020-07-09 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_danceclass_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='danceclass',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='account.TeacherAccount'),
            preserve_default=False,
        ),
    ]
