# Generated by Django 2.2.9 on 2020-07-09 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200709_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='danceclass',
            name='age_range',
            field=models.CharField(default=-1, max_length=7),
            preserve_default=False,
        ),
    ]
