# Generated by Django 2.2.9 on 2020-07-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_danceclass_age_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danceclass',
            name='day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=20),
        ),
    ]
