# Generated by Django 2.2.9 on 2020-07-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200711_0529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='danceclass',
            name='age_range',
        ),
        migrations.AddField(
            model_name='danceclass',
            name='max_age',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='danceclass',
            name='min_age',
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='danceclass',
            name='day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]),
        ),
    ]
