# Generated by Django 2.2.9 on 2020-07-16 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20200716_0449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='medical',
            new_name='notes',
        ),
    ]
