# Generated by Django 2.2.9 on 2020-07-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20200716_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentaccount',
            name='stripe_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
