# Generated by Django 2.2.9 on 2020-09-16 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20200916_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danceclass',
            name='secondary_image',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
