# Generated by Django 2.2.9 on 2020-09-16 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20200916_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentaccount',
            name='stripe_id',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
