# Generated by Django 2.2.9 on 2020-10-16 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auto_20200916_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentaccount',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
    ]
