# Generated by Django 2.2.9 on 2020-11-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_parentaccount_is_late'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danceclass',
            name='price_id',
            field=models.CharField(choices=[('price_1HRWnQIQ4hPK7zxOAOwjHQvv', 'Pre Creative Dance'), ('price_1HRWn3IQ4hPK7zxOb64qqBCG', 'Kinder Tap'), ('price_1HRWmmIQ4hPK7zxOQ8GKSplt', 'Intermediate Jazz'), ('price_1HmWiPIQ4hPK7zxOxdtqzmtJ', 'Kinder Jazz'), ('price_1HRWmYIQ4hPK7zxOEcN1irzM', 'Beginning 1 Jazz'), ('price_1HRWm7IQ4hPK7zxOh8w1Ksqy', 'Beginning 2 Ballet'), ('price_1HRWlgIQ4hPK7zxO3I0rUBCQ', 'Beginning 1 Ballet'), ('price_1HRWjxIQ4hPK7zxOxZKgZTg1', 'Pre Ballet'), ('price_1HRWHPIQ4hPK7zxOW0DfgEpX', 'Kinder Ballet')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='danceclass',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Full', 'Class is Full')], default='Inactive', max_length=20),
        ),
    ]
