# Generated by Django 2.2.9 on 2020-12-16 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_auto_20201112_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollment',
            name='semster',
            field=models.CharField(choices=[('Fall', 'Fall'), ('Winter', 'Winter'), ('Spring', 'Spring'), ('Summer', 'Summer')], default='Fall', max_length=10),
        ),
    ]
