# Generated by Django 2.2.9 on 2020-12-16 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_studentenrollment_semster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentenrollment',
            old_name='semster',
            new_name='semester',
        ),
    ]
