# Generated by Django 2.2.9 on 2021-03-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_auto_20201216_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='danceclass',
            name='end_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='danceclass',
            name='start_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='danceclass',
            name='dance_type',
            field=models.CharField(choices=[('Ballet', 'Ballet'), ('Jazz', 'Jazz'), ('Tap', 'Tap'), ('Modern', 'Modern'), ('Irish', 'Irish'), ('Ballroom', 'Ballroom'), ('Hip Hop', 'Hip Hop'), ('Creative Dance', 'Creative Dance'), ('Dance Camp', 'Dance Camp')], max_length=20),
        ),
        migrations.AlterField(
            model_name='danceclass',
            name='day',
            field=models.IntegerField(choices=[(-1, 'Monday - Friday'), (0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]),
        ),
    ]
