# Generated by Django 2.2.9 on 2021-03-17 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_auto_20210316_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='danceclass',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
