# Generated by Django 2.2.9 on 2021-06-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_danceclass_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='danceclass',
            name='class_type',
            field=models.CharField(choices=[('Fall Classes', 'Fall Classes'), ('Summer Camp', 'Summer Camp')], default='Summer Camps', max_length=40),
            preserve_default=False,
        ),
    ]
