# Generated by Django 2.2.9 on 2021-08-13 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_auto_20210716_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danceclass',
            name='dance_type',
            field=models.CharField(choices=[('Ballet', 'Ballet'), ('Jazz', 'Jazz'), ('Tap', 'Tap'), ('Modern', 'Modern'), ('Irish', 'Irish'), ('Ballroom', 'Ballroom'), ('Hip Hop', 'Hip Hop'), ('Creative Dance', 'Creative Dance'), ('Dance Camp', 'Dance Camp'), ('Dance', 'Dance')], max_length=20),
        ),
    ]
