# Generated by Django 2.2.9 on 2021-12-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_auto_20211112_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danceclass',
            name='class_type',
            field=models.CharField(choices=[('Fall Classes', 'Fall Classes'), ('Summer Camp', 'Summer Camp'), ('Winter Classes', 'Winter Classes')], max_length=40),
        ),
    ]
