# Generated by Django 2.2.28 on 2022-05-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_auto_20220409_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danceclass',
            name='curriculum',
            field=models.FilePathField(blank=True, null=True, path='/home/andrew/projects/ballet2020/staging/front/static/docs'),
        ),
        migrations.AlterField(
            model_name='danceclass',
            name='price_id',
            field=models.CharField(choices=[('None', 'None'), ('price_1Kwg8qIQ4hPK7zxOi4TiHUwj', 'Pre Creative Dance'), ('price_1Kwg5wIQ4hPK7zxOgI3lmQal', 'Kinder Tap'), ('price_1Kwg83IQ4hPK7zxO7zguIJxj', 'Intermediate Jazz'), ('price_1Kwg7PIQ4hPK7zxO6aMvc50D', 'Kinder Jazz'), ('price_1Kwg7dIQ4hPK7zxOFKam9nGi', 'Beginning 1 Jazz'), ('price_1Kwg5LIQ4hPK7zxOHOL8CiP1', 'Beginning 2 Ballet'), ('price_1Kwg54IQ4hPK7zxOVPpGKX6r', 'Beginning 1 Ballet'), ('price_1KwfyPIQ4hPK7zxOXBDsG5lN', 'Pre Ballet'), ('price_1Kwg32IQ4hPK7zxOZf3YKCph', 'Kinder Ballet'), ('price_1Kwg94IQ4hPK7zxOFOEInfyP', 'Kinder Creative'), ('price_1Kwg6vIQ4hPK7zxOKy6JSVp1', 'Beginning 1 Tap'), ('price_1Kwg5fIQ4hPK7zxOjkeTDxb4', 'Intermediate 1 Ballet'), ('price_1Kwg8OIQ4hPK7zxOQXjBKzBC', 'Mom & Tots Creative Dance'), ('price_1Kwg9XIQ4hPK7zxOrLgcCiHa', 'Beginning 1 Creative Dance')], default='', max_length=50),
        ),
    ]
