# Generated by Django 2.2.28 on 2022-06-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0040_auto_20220507_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danceclass',
            name='curriculum',
            field=models.FilePathField(blank=True, null=True, path='/home/andrew/projects/ballet2020/ballet2020/front/static/docs'),
        ),
        migrations.AlterField(
            model_name='danceclass',
            name='dance_type',
            field=models.CharField(choices=[('Ballet', 'Ballet'), ('Jazz', 'Jazz'), ('Tap', 'Tap'), ('Modern', 'Modern'), ('Irish', 'Irish'), ('Ballroom', 'Ballroom'), ('Hip Hop', 'Hip Hop'), ('Creative Dance', 'Creative Dance'), ('Dance Camp', 'Dance Camp'), ('Dance', 'Dance'), ('Contemporary', 'Contemporary'), ('Creative & Hip Hop', 'Creative & Hip Hop')], max_length=20),
        ),
    ]
