# Generated by Django 2.2.28 on 2022-06-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0042_auto_20220623_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danceclass',
            name='dance_type',
            field=models.CharField(choices=[('Ballet', 'Ballet'), ('Jazz', 'Jazz'), ('Tap', 'Tap'), ('Modern', 'Modern'), ('Irish', 'Irish'), ('Ballroom', 'Ballroom'), ('Hip Hop', 'Hip Hop'), ('Creative Dance', 'Creative Dance'), ('Dance Camp', 'Dance Camp'), ('Dance', 'Dance'), ('Contemporary', 'Contemporary'), ('Boys Creative & Hip Hop', 'Boys Creative & Hip Hop')], max_length=30),
        ),
    ]
