# Generated by Django 2.2.28 on 2022-07-16 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0043_auto_20220623_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='danceclass',
            name='curriculum',
            field=models.FilePathField(blank=True, null=True, path='/home/andrew/projects/ballet2020/staging/front/static/docs'),
        ),
        migrations.CreateModel(
            name='FreeClassRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_email', models.CharField(max_length=100)),
                ('num_students', models.IntegerField()),
                ('free_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.FreeClass')),
            ],
        ),
    ]
