# Generated by Django 2.2.28 on 2022-12-31 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0044_auto_20220716_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danceclass',
            name='curriculum',
            field=models.FilePathField(blank=True, null=True, path='/home/andrew/projects/ballet2020/ballet2020/front/static/docs'),
        ),
        migrations.AlterField(
            model_name='danceclass',
            name='level',
            field=models.CharField(choices=[('Parent & Tots', 'Parent & Tots'), ('Pre', 'Pre'), ('Kinder', 'Kinder'), ('Beginning 1', 'Beginning 1'), ('Beginning 2', 'Beginning 2'), ('Intermediate 1', 'Intermediate 1'), ('Intermediate 2', 'Intermediate 2'), ('Advanced 1', 'Advanced 1'), ('Advanced 2', 'Advanced 2'), ('Adult All Levels', 'Adult All Levels'), ('Adult Beginning', 'Adult Beginning'), ('Adult Advanced', 'Adult Advanced'), ('Homeschool', 'Homeschool')], max_length=20),
        ),
    ]
