# Generated by Django 2.2.28 on 2023-09-15 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0045_auto_20221231_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentaccount',
            name='skip_invoice',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='danceclass',
            name='dance_type',
            field=models.CharField(choices=[('Ballet', 'Ballet'), ('Jazz', 'Jazz'), ('Tap', 'Tap'), ('Modern', 'Modern'), ('Irish', 'Irish'), ('Ballroom', 'Ballroom'), ('Hip Hop', 'Hip Hop'), ('Creative Dance', 'Creative Dance'), ('Dance Camp', 'Dance Camp'), ('Dance', 'Dance'), ('Contemporary', 'Contemporary'), ('Boys Creative & Hip Hop', 'Boys Creative & Hip Hop'), ('Ballet/Tap Combo', 'Ballet/Tap Combo'), ('Tumbling', 'Tumbling'), ('Pre Pointe', 'Pre Pointe')], max_length=30),
        ),
        migrations.AlterField(
            model_name='danceclass',
            name='level',
            field=models.CharField(choices=[('Parent & Tots', 'Parent & Tots'), ('Pre', 'Pre'), ('Kinder', 'Kinder'), ('Beginning 1', 'Beginning 1'), ('Beginning 2', 'Beginning 2'), ('Intermediate 1', 'Intermediate 1'), ('Intermediate 2', 'Intermediate 2'), ('Advanced 1', 'Advanced 1'), ('Advanced 2', 'Advanced 2'), ('Adult All Levels', 'Adult All Levels'), ('Adult Beginning', 'Adult Beginning'), ('Adult Advanced', 'Adult Advanced'), ('Homeschool', 'Homeschool'), ('Special', 'Special')], max_length=20),
        ),
        migrations.AlterField(
            model_name='danceclass',
            name='price_id',
            field=models.CharField(choices=[('None', 'None'), ('price_1Kwg8qIQ4hPK7zxOi4TiHUwj', 'Pre Creative Dance'), ('price_1Kwg5wIQ4hPK7zxOgI3lmQal', 'Kinder Tap'), ('price_1N6f6YIQ4hPK7zxOiuw1zABv', 'Intermediate Jazz'), ('price_1Kwg7PIQ4hPK7zxO6aMvc50D', 'Kinder Jazz'), ('price_1N6fN1IQ4hPK7zxOjzrEfAZS', 'Beginning 1 Jazz'), ('price_1N6fPcIQ4hPK7zxO4opU9DCc', 'Beginning 2 Ballet'), ('price_1N6fO5IQ4hPK7zxO6negEDip', 'Beginning 1 Ballet'), ('price_1KwfyPIQ4hPK7zxOXBDsG5lN', 'Pre Ballet'), ('price_1Kwg32IQ4hPK7zxOZf3YKCph', 'Kinder Ballet'), ('price_1Kwg94IQ4hPK7zxOFOEInfyP', 'Kinder Creative'), ('price_1N6fQOIQ4hPK7zxOiDkcqCUp', 'Beginning 1 Tap'), ('price_1N6fQxIQ4hPK7zxOO5vui74W', 'Intermediate 1 Ballet'), ('price_1Kwg8OIQ4hPK7zxOQXjBKzBC', 'Parent & Tots Creative Dance'), ('price_1N6fRUIQ4hPK7zxOeijpPAAb', 'Beginning 1 Creative Dance'), ('price_1N6ftoIQ4hPK7zxOsqlgDurj', 'Beginning 2 Creative Dance'), ('price_1N6fz5IQ4hPK7zxO2rzZyjW1', 'Beginning 2 Jazz'), ('price_1N6gC9IQ4hPK7zxOj9dRUYcC', 'Kinder Tap/Ballet Combo'), ('price_1N6gGLIQ4hPK7zxOgg4fYN71', 'Kinder Tumbling'), ('price_1N6gFjIQ4hPK7zxOQrNikYJ9', 'Pre Pointe')], default='', max_length=50),
        ),
    ]
