# Generated by Django 2.2.28 on 2024-03-21 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0047_auto_20240321_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danceclass',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='danceclass',
            name='sale_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
