# Generated by Django 2.2.28 on 2024-08-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0050_auto_20240508_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentaccount',
            name='auto_pay',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='danceclass',
            name='curriculum',
            field=models.FilePathField(blank=True, null=True, path='/home/andrew/projects/ballet2020/staging/front/static/docs'),
        ),
    ]
